# Use Python runtime as a base image
FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Copy the Python script into the container
COPY run_p21.py /app/

RUN mkdir -p /output /data

# Install required dependencies
RUN pip install --no-cache-dir boto3

# Define the entrypoint to run the Python script
CMD ["python", "run_p21.py"]
